version: '3'

services:
  db:
    build: .
    container_name: db-container
    ports:
     - "5432:5432"
    volumes:
     - $PWD/docker/db:/docker-entrypoint-initdb.d
    env_file:
     - $PWD/docker/.env
  web:
    build:
      context: .
      dockerfile: DockerfileGo
    container_name: golang_container
    ports:
     - "8080:8080"
    depends_on:
     - db