version: '3'

services:
  db:
    image: shin0501/devi-db:latest
    container_name: db-container
    ports:
     - "5432:5432"
    env_file:
     - $PWD/docker/.env
  web:
    build: .
    container_name: web-container
    ports:
     - "8080:8080"
    depends_on:
     - db