version: '3'

services:
  db:
    image: postgres:11-alpine
    container_name: db-container
    ports:
     - "5432:5432"
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    env_file:
     - ./.env
